import Head from 'next/head'
import {
  Container,
  Main,
} from 'components/sharedstyles'
import { Auth, ThemeSupa } from '@supabase/auth-ui-react'
import { useSupabaseClient, useUser } from '@supabase/auth-helpers-react'
import styled from 'styled-components'
import Image from 'next/image'
import { useCallback, useEffect } from 'react'

export default function Home() {
  const supabaseClient = useSupabaseClient()
  const user = useUser()
  const userData = JSON.stringify(user)

  useEffect(() => console.log(user), [userData])
  const onSignOut = useCallback(() => supabaseClient.auth.signOut(), [supabaseClient])

  if (!user) {
    return <Auth
      redirectTo="http://localhost:3000/"
      appearance={{ theme: ThemeSupa }}
      supabaseClient={supabaseClient}
      providers={['github']}
    />
  }

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Welcome>
          <Greet>Hello, {user.user_metadata.name}!</Greet>
          <StyledImage src={user.user_metadata.avatar_url} alt="" width={40} height={40} />
        </Welcome>
        <Button onClick={onSignOut}>Log out</Button>
      </Main>
    </Container>
  )
}

const Greet = styled.span`
  line-height: 40px;
  vertical-align: middle;
`

const StyledImage = styled(Image)`
  border-radius: 20px;
`

const Welcome = styled.div`
  display: inline-grid;
  grid-template-columns: auto auto;
  gap: 10px;
`

const Button = styled.button`
`