import Head from 'next/head'
import { Cell, Container, HeadCell, ListTitle, Main, Row, Table } from 'components/sharedstyles'
import { useSupabaseClient } from '@supabase/auth-helpers-react'
import styled from 'styled-components'
import { useEffect, useState } from 'react'
import { Database } from 'database.types'
import { UserBar } from 'components/UserBar'
import { OrderListRow } from 'types'
import { OrderList } from 'components/OrdersList'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>🧸 Supabase Playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <UserBar />
        <ListTitle>Orders</ListTitle>
        <Orders />
      </Main>
    </Container>
  )
}

const Orders = () => {
  const supabaseClient = useSupabaseClient<Database>()
  const [orders, setOrders] = useState<OrderListRow[]>()

  useEffect(() => {
    (async function () {
      const { data, error } = await supabaseClient
        .from('OrderList')
        .select()

      if (!error) {
        setOrders(data)
      }
    })()
  }, [])

  return <OrdersTable>
    <Row>
      <HeadCell>List</HeadCell>
      <HeadCell>Owner</HeadCell>
    </Row>
    {orders?.map(orderList => <OrderList key={orderList.id} {...orderList} />)}
  </OrdersTable>
}

const OrdersTable = styled(Table)`
  ${Row} {
    grid-template-columns: auto 160px;
  }

  ${Cell}:last-of-type {
    justify-content: flex-end;
  }
`

